updated yml with env

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,15 +36,15 @@ jobs:
           script: |
             echo "🔧 Starting deploy on $(hostname)"
             cd /var/www/fs-be-node-project || {
-              echo "❌ Failed to find project directory!"
-              exit 1
+            echo "❌ Failed to find project directory!"
+            exit 1
             }
 
             echo "🌱 Writing .env file..."
-            cat <<EOF > .env
-            IGDB_CLIENT_ID=$IGDB_CLIENT_ID
-            IGDB_ACCESS_TOKEN=$IGDB_ACCESS_TOKEN
-            EOF
+cat <<EOF > .env
+IGDB_CLIENT_ID=$IGDB_CLIENT_ID
+IGDB_ACCESS_TOKEN=$IGDB_ACCESS_TOKEN
+EOF
 
             echo "📁 Project directory contents:"
             ls -la
